export const MOCK_SCENARIOS = [
  {
    id: 'b38612f7-17f2-48b2-aebf-51925fe4e47a',
    name: "Marcus \u2014 The Skeptic (SaaS)",
    prospect_name: "Marcus Holt",
    prospect_role: "VP of Sales",
    prospect_company: "CloudMetrics",
    industry: "SaaS",
    personality_type: "Skeptic",
    call_stage: "Cold Call",
    difficulty_rating: 3,
    default_product: "sales intelligence and pipeline visibility platform",
    language: "both",
  },
  {
    id: '4d9cb995-9adb-4a6a-98b7-48ea372df2d7',
    name: "James \u2014 The Skeptic (Healthcare)",
    prospect_name: "James Whitfield",
    prospect_role: "CFO",
    prospect_company: "HealthFirst Systems",
    industry: "Healthcare",
    personality_type: "Skeptic",
    call_stage: "Discovery Call",
    difficulty_rating: 2,
    default_product: "practice management and revenue cycle platform",
    language: "english",
  },
  {
    id: '3e9d239a-45de-4fbd-92ed-5b2b50599fa1',
    name: "William \u2014 The Skeptic (Legal)",
    prospect_name: "William Ashford",
    prospect_role: "Firm Administrator",
    prospect_company: "Ashford Legal Group",
    industry: "Legal",
    personality_type: "Skeptic",
    call_stage: "Demo / Pitch",
    difficulty_rating: 3,
    default_product: "legal practice management and billing platform",
    language: "english",
  },
  {
    id: '6af7489a-7821-4e13-bb89-daa0804b7871',
    name: "Angela \u2014 The Skeptic (Manufacturing)",
    prospect_name: "Angela Torres",
    prospect_role: "COO",
    prospect_company: "Precision Parts Inc",
    industry: "Manufacturing",
    personality_type: "Skeptic",
    call_stage: "Objection Handling",
    difficulty_rating: 4,
    default_product: "ERP and production scheduling platform",
    language: "both",
  },
  {
    id: '92a63320-d9d1-430c-9d4b-27948c1bb034',
    name: "Mark \u2014 The Skeptic (Real Estate)",
    prospect_name: "Mark Lawson",
    prospect_role: "Principal Broker",
    prospect_company: "Apex Properties",
    industry: "Real Estate",
    personality_type: "Skeptic",
    call_stage: "Closing Call",
    difficulty_rating: 4,
    default_product: "CRM and transaction management platform",
    language: "english",
  },
  {
    id: '7b02cc9d-798f-4a03-a4da-545354f272b5',
    name: "Richard \u2014 The Skeptic (Financial Services)",
    prospect_name: "Richard Harmon",
    prospect_role: "Wealth Manager",
    prospect_company: "Arbor Capital Partners",
    industry: "Financial Services",
    personality_type: "Skeptic",
    call_stage: "Follow-up",
    difficulty_rating: 2,
    default_product: "client relationship management and compliance platform",
    language: "english",
  },
  {
    id: 'dd1f1b3a-3195-4c39-a028-8d0c831f5749',
    name: "Eric \u2014 The Skeptic (EdTech)",
    prospect_name: "Eric Donovan",
    prospect_role: "Dean of Students",
    prospect_company: "Pacific Learning Institute",
    industry: "EdTech",
    personality_type: "Skeptic",
    call_stage: "Negotiation",
    difficulty_rating: 5,
    default_product: "enrollment management and student retention platform",
    language: "both",
  },
  {
    id: 'd96d1ab4-e998-4cbf-82a3-4f61d0b21767',
    name: "Roberto \u2014 The Ghost (Logistics)",
    prospect_name: "Roberto Silva",
    prospect_role: "VP of Operations",
    prospect_company: "Centrix Freight Solutions",
    industry: "Logistics",
    personality_type: "Ghost",
    call_stage: "Cold Call",
    difficulty_rating: 2,
    default_product: "route optimization and fleet management platform",
    language: "english",
  },
  {
    id: '7be769d9-e458-4a41-b5da-efcc8a0aa4d6',
    name: "Anna \u2014 The Ghost (Restaurant)",
    prospect_name: "Anna Chen",
    prospect_role: "Operations Manager",
    prospect_company: "Coastal Kitchen Group",
    industry: "Restaurant",
    personality_type: "Ghost",
    call_stage: "Discovery Call",
    difficulty_rating: 1,
    default_product: "POS and restaurant operations platform",
    language: "english",
  },
  {
    id: 'a5cbbd85-7c70-4dc5-b37b-84f3512f8162',
    name: "Linda \u2014 The Ghost (E-commerce)",
    prospect_name: "Linda Cooper",
    prospect_role: "VP Marketing",
    prospect_company: "SwiftGoods",
    industry: "E-commerce",
    personality_type: "Ghost",
    call_stage: "Demo / Pitch",
    difficulty_rating: 2,
    default_product: "customer acquisition and retention analytics platform",
    language: "both",
  },
  {
    id: '3d4ddc0b-bdd0-43f8-8fcb-ab04252ec9e0',
    name: "Sandra \u2014 The Ghost (Insurance)",
    prospect_name: "Sandra Park",
    prospect_role: "Director of Sales",
    prospect_company: "Apex Insurance Partners",
    industry: "Insurance",
    personality_type: "Ghost",
    call_stage: "Objection Handling",
    difficulty_rating: 3,
    default_product: "agency CRM and renewal management platform",
    language: "english",
  },
  {
    id: '778f1d7c-59ff-4db8-bd26-8c018ae0f00e',
    name: "Angela \u2014 The Ghost (Hospitality)",
    prospect_name: "Angela Morales",
    prospect_role: "COO",
    prospect_company: "Apex Hospitality Group",
    industry: "Hospitality",
    personality_type: "Ghost",
    call_stage: "Closing Call",
    difficulty_rating: 3,
    default_product: "revenue management and OTA optimization platform",
    language: "english",
  },
  {
    id: 'e3437bb9-8dfd-4708-b57b-7756dd146894',
    name: "Daniel \u2014 The Ghost (Marketing Agency)",
    prospect_name: "Daniel West",
    prospect_role: "Founder/CEO",
    prospect_company: "Gravity Digital",
    industry: "Marketing Agency",
    personality_type: "Ghost",
    call_stage: "Follow-up",
    difficulty_rating: 1,
    default_product: "project management and client reporting platform",
    language: "both",
  },
  {
    id: '4fb5b0a7-3fd5-4cdd-a71c-5f1ef6692c91',
    name: "Stephanie \u2014 The Ghost (Fitness/Wellness)",
    prospect_name: "Stephanie Liu",
    prospect_role: "VP Operations",
    prospect_company: "CoreFit Franchise",
    industry: "Fitness/Wellness",
    personality_type: "Ghost",
    call_stage: "Negotiation",
    difficulty_rating: 4,
    default_product: "membership management and studio scheduling platform",
    language: "english",
  },
  {
    id: '79fd789f-627e-4381-8620-ee4b55c40285',
    name: "Mark \u2014 The Price Objector (Recruiting/Staffing)",
    prospect_name: "Mark Donovan",
    prospect_role: "Managing Director",
    prospect_company: "TalentForce Partners",
    industry: "Recruiting/Staffing",
    personality_type: "Price Objector",
    call_stage: "Cold Call",
    difficulty_rating: 2,
    default_product: "ATS and sourcing automation platform",
    language: "english",
  },
  {
    id: '2d6ef551-58a6-439b-b2de-c90ad37369c2',
    name: "Victoria \u2014 The Price Objector (Construction)",
    prospect_name: "Victoria Hanson",
    prospect_role: "Project Manager",
    prospect_company: "Cornerstone Construction",
    industry: "Construction",
    personality_type: "Price Objector",
    call_stage: "Discovery Call",
    difficulty_rating: 1,
    default_product: "project management and estimating platform",
    language: "both",
  },
  {
    id: '4237030a-1e69-4728-9856-802be588028a',
    name: "Susan \u2014 The Price Objector (Retail)",
    prospect_name: "Susan Kang",
    prospect_role: "Store Operations Manager",
    prospect_company: "Apex Retail Group",
    industry: "Retail",
    personality_type: "Price Objector",
    call_stage: "Demo / Pitch",
    difficulty_rating: 2,
    default_product: "inventory management and retail analytics platform",
    language: "english",
  },
  {
    id: 'b32fdd2c-83ce-4a5b-8154-2e4183e1d700',
    name: "Julia \u2014 The Price Objector (Consulting)",
    prospect_name: "Julia Martin",
    prospect_role: "VP Consulting",
    prospect_company: "Meridian Consulting",
    industry: "Consulting",
    personality_type: "Price Objector",
    call_stage: "Objection Handling",
    difficulty_rating: 3,
    default_product: "CRM and proposal automation platform",
    language: "english",
  },
  {
    id: '2a9b1ec8-485e-4a10-b08b-f6a30577ed8a',
    name: "Joyce \u2014 The Price Objector (Non-profit)",
    prospect_name: "Joyce Kim",
    prospect_role: "Chief Development Officer",
    prospect_company: "Core Community Works",
    industry: "Non-profit",
    personality_type: "Price Objector",
    call_stage: "Closing Call",
    difficulty_rating: 3,
    default_product: "donor management and fundraising platform",
    language: "both",
  },
  {
    id: '78882df9-4f01-4fa9-b14e-c4a7cb6f1557',
    name: "Richard \u2014 The Price Objector (Media/Publishing)",
    prospect_name: "Richard Farley",
    prospect_role: "Publisher",
    prospect_company: "Meridian Media Group",
    industry: "Media/Publishing",
    personality_type: "Price Objector",
    call_stage: "Follow-up",
    difficulty_rating: 1,
    default_product: "audience analytics and monetization platform",
    language: "english",
  },
  {
    id: '65eca8a9-46c2-4aa9-8d9a-e672ed86b674',
    name: "Diana \u2014 The Price Objector (SaaS)",
    prospect_name: "Diana Reyes",
    prospect_role: "CRO",
    prospect_company: "Scalebound AI",
    industry: "SaaS",
    personality_type: "Price Objector",
    call_stage: "Negotiation",
    difficulty_rating: 4,
    default_product: "sales intelligence and pipeline visibility platform",
    language: "english",
  },
  {
    id: 'cc061591-7a21-48a2-a763-ff7126f50f6c',
    name: "Dr \u2014 The Overanalyzer (Healthcare)",
    prospect_name: "Dr. Sandra Ruiz",
    prospect_role: "Practice Owner",
    prospect_company: "Sunrise Medical Group",
    industry: "Healthcare",
    personality_type: "Overanalyzer",
    call_stage: "Cold Call",
    difficulty_rating: 3,
    default_product: "practice management and revenue cycle platform",
    language: "both",
  },
  {
    id: '5ddd4a78-df49-45bd-b9bb-d771dc77eda1',
    name: "Eric \u2014 The Overanalyzer (EdTech)",
    prospect_name: "Eric Donovan",
    prospect_role: "Dean of Students",
    prospect_company: "Pacific Learning Institute",
    industry: "EdTech",
    personality_type: "Overanalyzer",
    call_stage: "Discovery Call",
    difficulty_rating: 2,
    default_product: "enrollment management and student retention platform",
    language: "english",
  },
  {
    id: '6b5c283d-fd50-480b-b7bc-6555a18944b4',
    name: "Anthony \u2014 The Overanalyzer (Financial Services)",
    prospect_name: "Anthony Greco",
    prospect_role: "VP Advisor",
    prospect_company: "Meridian Wealth Group",
    industry: "Financial Services",
    personality_type: "Overanalyzer",
    call_stage: "Demo / Pitch",
    difficulty_rating: 3,
    default_product: "client relationship management and compliance platform",
    language: "english",
  },
  {
    id: 'ed7824ba-263b-4c00-97a8-3b28cbfc7974',
    name: "Diane \u2014 The Overanalyzer (Logistics)",
    prospect_name: "Diane Lim",
    prospect_role: "COO",
    prospect_company: "Momentum Freight",
    industry: "Logistics",
    personality_type: "Overanalyzer",
    call_stage: "Objection Handling",
    difficulty_rating: 4,
    default_product: "route optimization and fleet management platform",
    language: "both",
  },
  {
    id: '81a681f5-5166-416b-a46a-06bd7ea98590',
    name: "John \u2014 The Overanalyzer (Insurance)",
    prospect_name: "John Macy",
    prospect_role: "Principal Agent",
    prospect_company: "Summit Benefits Group",
    industry: "Insurance",
    personality_type: "Overanalyzer",
    call_stage: "Closing Call",
    difficulty_rating: 4,
    default_product: "agency CRM and renewal management platform",
    language: "english",
  },
  {
    id: 'b3d82169-d04c-4d63-951e-61c4dc1b3dd3',
    name: "Thomas \u2014 The Overanalyzer (Consulting)",
    prospect_name: "Thomas Elliot",
    prospect_role: "Partner",
    prospect_company: "Stratford Consulting Group",
    industry: "Consulting",
    personality_type: "Overanalyzer",
    call_stage: "Follow-up",
    difficulty_rating: 2,
    default_product: "CRM and proposal automation platform",
    language: "english",
  },
  {
    id: '74c52948-dce9-449f-98e8-a52c6805c816',
    name: "Eric \u2014 The Overanalyzer (Non-profit)",
    prospect_name: "Eric Washington",
    prospect_role: "VP of Development",
    prospect_company: "Rising Tide Alliance",
    industry: "Non-profit",
    personality_type: "Overanalyzer",
    call_stage: "Negotiation",
    difficulty_rating: 5,
    default_product: "donor management and fundraising platform",
    language: "both",
  },
  {
    id: 'ba220b0d-8132-45bc-81b1-e92578f2beb9',
    name: "Robert \u2014 The Gatekeeper (Manufacturing)",
    prospect_name: "Robert Gunther",
    prospect_role: "VP of Operations",
    prospect_company: "Midwest Fabrication Co",
    industry: "Manufacturing",
    personality_type: "Gatekeeper",
    call_stage: "Cold Call",
    difficulty_rating: 3,
    default_product: "ERP and production scheduling platform",
    language: "english",
  },
  {
    id: 'd690dd19-528a-4e01-b068-54176b10e613',
    name: "Diana \u2014 The Gatekeeper (SaaS)",
    prospect_name: "Diana Reyes",
    prospect_role: "CRO",
    prospect_company: "Scalebound AI",
    industry: "SaaS",
    personality_type: "Gatekeeper",
    call_stage: "Discovery Call",
    difficulty_rating: 2,
    default_product: "sales intelligence and pipeline visibility platform",
    language: "english",
  },
  {
    id: 'eebf1355-24df-42f6-9279-d730e6b14df9',
    name: "Patricia \u2014 The Gatekeeper (Healthcare)",
    prospect_name: "Patricia Morales",
    prospect_role: "VP Operations",
    prospect_company: "CareConnect Health",
    industry: "Healthcare",
    personality_type: "Gatekeeper",
    call_stage: "Demo / Pitch",
    difficulty_rating: 3,
    default_product: "practice management and revenue cycle platform",
    language: "both",
  },
  {
    id: '0a73cd73-d84c-4380-958f-a7ecc961861d',
    name: "Julia \u2014 The Gatekeeper (Legal)",
    prospect_name: "Julia Stern",
    prospect_role: "COO",
    prospect_company: "Sterling Law Partners",
    industry: "Legal",
    personality_type: "Gatekeeper",
    call_stage: "Objection Handling",
    difficulty_rating: 4,
    default_product: "legal practice management and billing platform",
    language: "english",
  },
  {
    id: '8563f478-6978-4bf4-ab87-70be0cc36248',
    name: "Carlos \u2014 The Gatekeeper (Restaurant)",
    prospect_name: "Carlos Diaz",
    prospect_role: "Multi-Unit Owner",
    prospect_company: "The Corner Table Group",
    industry: "Restaurant",
    personality_type: "Gatekeeper",
    call_stage: "Closing Call",
    difficulty_rating: 4,
    default_product: "POS and restaurant operations platform",
    language: "english",
  },
  {
    id: '80a54cae-786d-4c18-8590-b686aabdf887',
    name: "Daniel \u2014 The Gatekeeper (Marketing Agency)",
    prospect_name: "Daniel West",
    prospect_role: "Founder/CEO",
    prospect_company: "Gravity Digital",
    industry: "Marketing Agency",
    personality_type: "Gatekeeper",
    call_stage: "Follow-up",
    difficulty_rating: 2,
    default_product: "project management and client reporting platform",
    language: "both",
  },
  {
    id: '279436cc-910c-4458-a32e-6184f8c17b77',
    name: "Stephanie \u2014 The Gatekeeper (Fitness/Wellness)",
    prospect_name: "Stephanie Liu",
    prospect_role: "VP Operations",
    prospect_company: "CoreFit Franchise",
    industry: "Fitness/Wellness",
    personality_type: "Gatekeeper",
    call_stage: "Negotiation",
    difficulty_rating: 5,
    default_product: "membership management and studio scheduling platform",
    language: "english",
  },
  {
    id: '2a3ddabf-7013-4138-9c38-d92f5e28aa7d',
    name: "Victoria \u2014 The Burned Buyer (EdTech)",
    prospect_name: "Victoria Huang",
    prospect_role: "VP Enrollment",
    prospect_company: "Westbrook Academy",
    industry: "EdTech",
    personality_type: "Burned Buyer",
    call_stage: "Cold Call",
    difficulty_rating: 4,
    default_product: "enrollment management and student retention platform",
    language: "english",
  },
  {
    id: 'ff759762-1b8c-4c33-a938-1fafc5b4db90',
    name: "Linda \u2014 The Burned Buyer (Manufacturing)",
    prospect_name: "Linda Vasquez",
    prospect_role: "Plant Manager",
    prospect_company: "Apex Manufacturing",
    industry: "Manufacturing",
    personality_type: "Burned Buyer",
    call_stage: "Discovery Call",
    difficulty_rating: 3,
    default_product: "ERP and production scheduling platform",
    language: "both",
  },
  {
    id: '4f126968-eafb-4866-8c03-7c2501920520',
    name: "Charles \u2014 The Burned Buyer (Logistics)",
    prospect_name: "Charles Okafor",
    prospect_role: "Fleet Manager",
    prospect_company: "Apex 3PL",
    industry: "Logistics",
    personality_type: "Burned Buyer",
    call_stage: "Demo / Pitch",
    difficulty_rating: 4,
    default_product: "route optimization and fleet management platform",
    language: "english",
  },
  {
    id: '4e30b0cb-dc8e-4fd1-b5db-e8e58636707d',
    name: "Nicole \u2014 The Burned Buyer (Real Estate)",
    prospect_name: "Nicole Estrada",
    prospect_role: "Director of Sales",
    prospect_company: "Metro Living Group",
    industry: "Real Estate",
    personality_type: "Burned Buyer",
    call_stage: "Objection Handling",
    difficulty_rating: 5,
    default_product: "CRM and transaction management platform",
    language: "english",
  },
  {
    id: '04290fce-3373-4536-a4d2-d485c6576382',
    name: "Joseph \u2014 The Burned Buyer (Financial Services)",
    prospect_name: "Joseph Tanaka",
    prospect_role: "Partner",
    prospect_company: "Clarity Capital",
    industry: "Financial Services",
    personality_type: "Burned Buyer",
    call_stage: "Closing Call",
    difficulty_rating: 5,
    default_product: "client relationship management and compliance platform",
    language: "both",
  },
  {
    id: 'd8c82955-6df8-4cfb-8f16-6324f735ff8b',
    name: "Dr \u2014 The Burned Buyer (Healthcare)",
    prospect_name: "Dr. Sandra Ruiz",
    prospect_role: "Practice Owner",
    prospect_company: "Sunrise Medical Group",
    industry: "Healthcare",
    personality_type: "Burned Buyer",
    call_stage: "Follow-up",
    difficulty_rating: 3,
    default_product: "practice management and revenue cycle platform",
    language: "english",
  },
  {
    id: '7fcbeab7-7fad-48e5-9d8f-9d8abbf8408e',
    name: "Patricia \u2014 The Burned Buyer (Insurance)",
    prospect_name: "Patricia Lee",
    prospect_role: "VP of Operations",
    prospect_company: "Shield Direct",
    industry: "Insurance",
    personality_type: "Burned Buyer",
    call_stage: "Negotiation",
    difficulty_rating: 5,
    default_product: "agency CRM and renewal management platform",
    language: "english",
  },
  {
    id: '5aeb8d36-0e29-4e00-96b3-c1cd62f39e14',
    name: "Miguel \u2014 The Friendly Waster (Restaurant)",
    prospect_name: "Miguel Torres",
    prospect_role: "Owner",
    prospect_company: "La Cocina de Miguel",
    industry: "Restaurant",
    personality_type: "Friendly Waster",
    call_stage: "Cold Call",
    difficulty_rating: 3,
    default_product: "POS and restaurant operations platform",
    language: "both",
  },
  {
    id: '3f5b8104-c864-413c-b791-24d6e17d75eb',
    name: "Amanda \u2014 The Friendly Waster (Marketing Agency)",
    prospect_name: "Amanda Cruz",
    prospect_role: "Account Director",
    prospect_company: "Momentum Agency",
    industry: "Marketing Agency",
    personality_type: "Friendly Waster",
    call_stage: "Discovery Call",
    difficulty_rating: 2,
    default_product: "project management and client reporting platform",
    language: "english",
  },
  {
    id: 'e406b858-8620-4482-830c-5c2dcb972096',
    name: "Melissa \u2014 The Friendly Waster (Hospitality)",
    prospect_name: "Melissa Grant",
    prospect_role: "Revenue Manager",
    prospect_company: "Summit Conference Center",
    industry: "Hospitality",
    personality_type: "Friendly Waster",
    call_stage: "Demo / Pitch",
    difficulty_rating: 3,
    default_product: "revenue management and OTA optimization platform",
    language: "english",
  },
  {
    id: 'd4282ac7-b710-4784-8558-5399c3e0a876',
    name: "Julia \u2014 The Friendly Waster (Consulting)",
    prospect_name: "Julia Martin",
    prospect_role: "VP Consulting",
    prospect_company: "Meridian Consulting",
    industry: "Consulting",
    personality_type: "Friendly Waster",
    call_stage: "Objection Handling",
    difficulty_rating: 4,
    default_product: "CRM and proposal automation platform",
    language: "both",
  },
  {
    id: '9707af9f-641c-4c48-a7cc-4f82ae50b907',
    name: "Joseph \u2014 The Friendly Waster (Media/Publishing)",
    prospect_name: "Joseph Ramos",
    prospect_role: "COO",
    prospect_company: "Core Media Partners",
    industry: "Media/Publishing",
    personality_type: "Friendly Waster",
    call_stage: "Closing Call",
    difficulty_rating: 4,
    default_product: "audience analytics and monetization platform",
    language: "english",
  },
  {
    id: '067b88eb-43e0-4db3-83ae-4897955466a9',
    name: "Victoria \u2014 The Friendly Waster (Non-profit)",
    prospect_name: "Victoria Cole",
    prospect_role: "Executive Director",
    prospect_company: "Lighthouse Community Foundation",
    industry: "Non-profit",
    personality_type: "Friendly Waster",
    call_stage: "Follow-up",
    difficulty_rating: 2,
    default_product: "donor management and fundraising platform",
    language: "english",
  },
  {
    id: 'ef4aa95a-d0cf-4735-9e4b-7b5e57852fa2',
    name: "Evelyn \u2014 The Friendly Waster (Retail)",
    prospect_name: "Evelyn Torres",
    prospect_role: "Merchandising Director",
    prospect_company: "NorthGate Stores",
    industry: "Retail",
    personality_type: "Friendly Waster",
    call_stage: "Negotiation",
    difficulty_rating: 5,
    default_product: "inventory management and retail analytics platform",
    language: "both",
  },
  {
    id: '00822ce1-7f32-4263-ba38-2a660e564c09',
    name: "Dr \u2014 The Urgency Seeker (Healthcare)",
    prospect_name: "Dr. Sandra Ruiz",
    prospect_role: "Practice Owner",
    prospect_company: "Sunrise Medical Group",
    industry: "Healthcare",
    personality_type: "Urgency Seeker",
    call_stage: "Cold Call",
    difficulty_rating: 2,
    default_product: "practice management and revenue cycle platform",
    language: "english",
  },
  {
    id: '4631ff49-2ba5-4011-a4c6-9b9f234e9ec9',
    name: "Diana \u2014 The Urgency Seeker (SaaS)",
    prospect_name: "Diana Reyes",
    prospect_role: "CRO",
    prospect_company: "Scalebound AI",
    industry: "SaaS",
    personality_type: "Urgency Seeker",
    call_stage: "Discovery Call",
    difficulty_rating: 1,
    default_product: "sales intelligence and pipeline visibility platform",
    language: "english",
  },
  {
    id: 'acbd6149-8486-4da1-9205-72ddf2f3bd43',
    name: "Charles \u2014 The Urgency Seeker (Logistics)",
    prospect_name: "Charles Okafor",
    prospect_role: "Fleet Manager",
    prospect_company: "Apex 3PL",
    industry: "Logistics",
    personality_type: "Urgency Seeker",
    call_stage: "Demo / Pitch",
    difficulty_rating: 2,
    default_product: "route optimization and fleet management platform",
    language: "both",
  },
  {
    id: 'ce5bb0e8-2fc6-4681-b558-7dba920863ab',
    name: "Sandra \u2014 The Urgency Seeker (Insurance)",
    prospect_name: "Sandra Park",
    prospect_role: "Director of Sales",
    prospect_company: "Apex Insurance Partners",
    industry: "Insurance",
    personality_type: "Urgency Seeker",
    call_stage: "Objection Handling",
    difficulty_rating: 3,
    default_product: "agency CRM and renewal management platform",
    language: "english",
  },
  {
    id: '79d3796d-fce0-4db2-a9a1-34dc73efbf63',
    name: "Carlos \u2014 The Urgency Seeker (Restaurant)",
    prospect_name: "Carlos Diaz",
    prospect_role: "Multi-Unit Owner",
    prospect_company: "The Corner Table Group",
    industry: "Restaurant",
    personality_type: "Urgency Seeker",
    call_stage: "Closing Call",
    difficulty_rating: 3,
    default_product: "POS and restaurant operations platform",
    language: "english",
  },
  {
    id: 'a2c8e82b-6bc6-464f-afd4-9fb914254c56',
    name: "Mark \u2014 The Urgency Seeker (Recruiting/Staffing)",
    prospect_name: "Mark Donovan",
    prospect_role: "Managing Director",
    prospect_company: "TalentForce Partners",
    industry: "Recruiting/Staffing",
    personality_type: "Urgency Seeker",
    call_stage: "Follow-up",
    difficulty_rating: 1,
    default_product: "ATS and sourcing automation platform",
    language: "both",
  },
  {
    id: '63bd6197-4267-42b1-a43d-05bfbc2a19ba',
    name: "Victoria \u2014 The Urgency Seeker (Construction)",
    prospect_name: "Victoria Hanson",
    prospect_role: "Project Manager",
    prospect_company: "Cornerstone Construction",
    industry: "Construction",
    personality_type: "Urgency Seeker",
    call_stage: "Negotiation",
    difficulty_rating: 4,
    default_product: "project management and estimating platform",
    language: "english",
  },
  {
    id: '78c4ff11-346b-4cce-900f-0c6baf5d9c23',
    name: "Richard \u2014 The Process Person (Financial Services)",
    prospect_name: "Richard Harmon",
    prospect_role: "Wealth Manager",
    prospect_company: "Arbor Capital Partners",
    industry: "Financial Services",
    personality_type: "Process Person",
    call_stage: "Cold Call",
    difficulty_rating: 3,
    default_product: "client relationship management and compliance platform",
    language: "english",
  },
  {
    id: '290da167-8d1d-417a-ba73-84cee4868549',
    name: "James \u2014 The Process Person (Healthcare)",
    prospect_name: "James Whitfield",
    prospect_role: "CFO",
    prospect_company: "HealthFirst Systems",
    industry: "Healthcare",
    personality_type: "Process Person",
    call_stage: "Discovery Call",
    difficulty_rating: 2,
    default_product: "practice management and revenue cycle platform",
    language: "both",
  },
  {
    id: 'dd8f15d9-4c43-433c-acf3-87c4706af8b4',
    name: "William \u2014 The Process Person (Legal)",
    prospect_name: "William Ashford",
    prospect_role: "Firm Administrator",
    prospect_company: "Ashford Legal Group",
    industry: "Legal",
    personality_type: "Process Person",
    call_stage: "Demo / Pitch",
    difficulty_rating: 3,
    default_product: "legal practice management and billing platform",
    language: "english",
  },
  {
    id: '263e5e2b-3b2f-4bfa-937f-3359fc78cab4',
    name: "Sandra \u2014 The Process Person (Insurance)",
    prospect_name: "Sandra Park",
    prospect_role: "Director of Sales",
    prospect_company: "Apex Insurance Partners",
    industry: "Insurance",
    personality_type: "Process Person",
    call_stage: "Objection Handling",
    difficulty_rating: 4,
    default_product: "agency CRM and renewal management platform",
    language: "english",
  },
  {
    id: '9ad91859-5719-44c4-bf7e-1c30b1b7d45a',
    name: "Joyce \u2014 The Process Person (EdTech)",
    prospect_name: "Joyce Reyes",
    prospect_role: "COO",
    prospect_company: "Summit Online College",
    industry: "EdTech",
    personality_type: "Process Person",
    call_stage: "Closing Call",
    difficulty_rating: 4,
    default_product: "enrollment management and student retention platform",
    language: "both",
  },
  {
    id: '4a0d4190-25d5-4e03-ae0a-e696515864c0',
    name: "Richard \u2014 The Process Person (Construction)",
    prospect_name: "Richard Gutierrez",
    prospect_role: "VP of Operations",
    prospect_company: "Granite Build Group",
    industry: "Construction",
    personality_type: "Process Person",
    call_stage: "Follow-up",
    difficulty_rating: 2,
    default_product: "project management and estimating platform",
    language: "english",
  },
  {
    id: '98f552ca-2424-4d27-90a6-3826e10c52f3',
    name: "Eric \u2014 The Process Person (Non-profit)",
    prospect_name: "Eric Washington",
    prospect_role: "VP of Development",
    prospect_company: "Rising Tide Alliance",
    industry: "Non-profit",
    personality_type: "Process Person",
    call_stage: "Negotiation",
    difficulty_rating: 5,
    default_product: "donor management and fundraising platform",
    language: "english",
  },
  {
    id: '1143d533-a819-4eb4-b949-60cc1a74be1f',
    name: "Marcus \u2014 The Alpha (SaaS)",
    prospect_name: "Marcus Holt",
    prospect_role: "VP of Sales",
    prospect_company: "CloudMetrics",
    industry: "SaaS",
    personality_type: "Alpha",
    call_stage: "Cold Call",
    difficulty_rating: 4,
    default_product: "sales intelligence and pipeline visibility platform",
    language: "both",
  },
  {
    id: '932127dd-6495-48d4-bb66-f9dbb0a96586',
    name: "Catherine \u2014 The Alpha (Consulting)",
    prospect_name: "Catherine Wong",
    prospect_role: "Managing Director",
    prospect_company: "Apex Strategy Partners",
    industry: "Consulting",
    personality_type: "Alpha",
    call_stage: "Discovery Call",
    difficulty_rating: 3,
    default_product: "CRM and proposal automation platform",
    language: "english",
  },
  {
    id: '4432d61c-bfa4-4d5d-b844-d11b9165ed23',
    name: "Anthony \u2014 The Alpha (Financial Services)",
    prospect_name: "Anthony Greco",
    prospect_role: "VP Advisor",
    prospect_company: "Meridian Wealth Group",
    industry: "Financial Services",
    personality_type: "Alpha",
    call_stage: "Demo / Pitch",
    difficulty_rating: 4,
    default_product: "client relationship management and compliance platform",
    language: "english",
  },
  {
    id: '5a1a62dc-6ed7-4f0f-ba6e-060bb3b20ae1',
    name: "Nicole \u2014 The Alpha (Real Estate)",
    prospect_name: "Nicole Estrada",
    prospect_role: "Director of Sales",
    prospect_company: "Metro Living Group",
    industry: "Real Estate",
    personality_type: "Alpha",
    call_stage: "Objection Handling",
    difficulty_rating: 5,
    default_product: "CRM and transaction management platform",
    language: "both",
  },
  {
    id: 'ffabb28a-535f-4312-8fb4-b3cdbdbe67e6',
    name: "Donald \u2014 The Alpha (Manufacturing)",
    prospect_name: "Donald Hicks",
    prospect_role: "Production Manager",
    prospect_company: "Cascade Metal Works",
    industry: "Manufacturing",
    personality_type: "Alpha",
    call_stage: "Closing Call",
    difficulty_rating: 5,
    default_product: "ERP and production scheduling platform",
    language: "english",
  },
  {
    id: '65a0b073-cd5d-47f1-9fbb-f237cdff27aa',
    name: "Miguel \u2014 The Alpha (Restaurant)",
    prospect_name: "Miguel Torres",
    prospect_role: "Owner",
    prospect_company: "La Cocina de Miguel",
    industry: "Restaurant",
    personality_type: "Alpha",
    call_stage: "Follow-up",
    difficulty_rating: 3,
    default_product: "POS and restaurant operations platform",
    language: "english",
  },
  {
    id: '4dbeb1f6-9cb6-40ab-935b-506cb2b4c9a8',
    name: "Stephanie \u2014 The Alpha (Media/Publishing)",
    prospect_name: "Stephanie Adler",
    prospect_role: "VP Digital",
    prospect_company: "Coastal Content Networks",
    industry: "Media/Publishing",
    personality_type: "Alpha",
    call_stage: "Negotiation",
    difficulty_rating: 5,
    default_product: "audience analytics and monetization platform",
    language: "both",
  },
  {
    id: 'f60add75-f62c-4862-8223-2300b402263b',
    name: "Marcus \u2014 Deep Dive: SaaS (Skeptic)",
    prospect_name: "Marcus Holt",
    prospect_role: "CRO",
    prospect_company: "Scalebound AI",
    industry: "SaaS",
    personality_type: "Skeptic",
    call_stage: "Discovery Call",
    difficulty_rating: 3,
    default_product: "sales intelligence and pipeline visibility platform",
    language: "english",
  },
  {
    id: '5ac7b2a6-763d-4745-95b1-1078e38432ac',
    name: "Ethan \u2014 Deep Dive: SaaS (Burned Buyer)",
    prospect_name: "Ethan Cole",
    prospect_role: "Head of Revenue",
    prospect_company: "VeloStack",
    industry: "SaaS",
    personality_type: "Burned Buyer",
    call_stage: "Objection Handling",
    difficulty_rating: 5,
    default_product: "sales intelligence and pipeline visibility platform",
    language: "english",
  },
  {
    id: '3d9cf23c-432b-4b17-ab4d-278c36894da7',
    name: "Elena \u2014 Deep Dive: Healthcare (Alpha)",
    prospect_name: "Elena Park",
    prospect_role: "Practice Owner",
    prospect_company: "Sunrise Medical Group",
    industry: "Healthcare",
    personality_type: "Alpha",
    call_stage: "Demo / Pitch",
    difficulty_rating: 5,
    default_product: "practice management and revenue cycle platform",
    language: "english",
  },
  {
    id: 'b0d5d308-200f-4411-8436-4dac01e65a8e',
    name: "James \u2014 Deep Dive: Healthcare (Process Person)",
    prospect_name: "James Whitfield",
    prospect_role: "VP Operations",
    prospect_company: "CareConnect Health",
    industry: "Healthcare",
    personality_type: "Process Person",
    call_stage: "Negotiation",
    difficulty_rating: 5,
    default_product: "practice management and revenue cycle platform",
    language: "english",
  },
  {
    id: '81d0f0ea-9f88-44dd-a2a6-7b2d295fb211',
    name: "Nicole \u2014 Deep Dive: Real Estate (Ghost)",
    prospect_name: "Nicole Estrada",
    prospect_role: "Principal Broker",
    prospect_company: "Apex Properties",
    industry: "Real Estate",
    personality_type: "Ghost",
    call_stage: "Cold Call",
    difficulty_rating: 3,
    default_product: "CRM and transaction management platform",
    language: "english",
  },
  {
    id: '2353a554-17bb-4d27-a28d-0171ad46b093',
    name: "Carlos \u2014 Deep Dive: Real Estate (Urgency Seeker)",
    prospect_name: "Carlos Mendoza",
    prospect_role: "Team Lead",
    prospect_company: "HomeFront Properties",
    industry: "Real Estate",
    personality_type: "Urgency Seeker",
    call_stage: "Closing Call",
    difficulty_rating: 4,
    default_product: "CRM and transaction management platform",
    language: "english",
  },
  {
    id: '15923904-0fb3-40cc-9552-ff44e6436bd0',
    name: "William \u2014 Deep Dive: Legal (Price Objector)",
    prospect_name: "William Ashford",
    prospect_role: "COO",
    prospect_company: "Sterling Law Partners",
    industry: "Legal",
    personality_type: "Price Objector",
    call_stage: "Discovery Call",
    difficulty_rating: 2,
    default_product: "legal practice management and billing platform",
    language: "english",
  },
  {
    id: 'b94b21ee-ea43-46f7-999b-13add732160b',
    name: "David \u2014 Deep Dive: Legal (Overanalyzer)",
    prospect_name: "David Kwan",
    prospect_role: "Managing Partner",
    prospect_company: "Morrison & Burke LLP",
    industry: "Legal",
    personality_type: "Overanalyzer",
    call_stage: "Objection Handling",
    difficulty_rating: 5,
    default_product: "legal practice management and billing platform",
    language: "english",
  },
  {
    id: 'a5e6a134-1e89-49aa-ac1d-c119d27e0750',
    name: "Susan \u2014 Deep Dive: Logistics (Burned Buyer)",
    prospect_name: "Susan Finley",
    prospect_role: "Fleet Manager",
    prospect_company: "Apex 3PL",
    industry: "Logistics",
    personality_type: "Burned Buyer",
    call_stage: "Cold Call",
    difficulty_rating: 5,
    default_product: "route optimization and fleet management platform",
    language: "english",
  },
  {
    id: '2e30ad46-f800-45e6-b103-37b8e0d42824',
    name: "Diane \u2014 Deep Dive: Logistics (Skeptic)",
    prospect_name: "Diane Lim",
    prospect_role: "Director of Logistics",
    prospect_company: "Cascade Transport Group",
    industry: "Logistics",
    personality_type: "Skeptic",
    call_stage: "Negotiation",
    difficulty_rating: 5,
    default_product: "route optimization and fleet management platform",
    language: "english",
  },
  {
    id: '9e1b85a3-f165-4600-a484-ec54d034f197',
    name: "Richard \u2014 Deep Dive: Financial Services (Process Person)",
    prospect_name: "Richard Harmon",
    prospect_role: "RIA Principal",
    prospect_company: "Summit Financial Advisors",
    industry: "Financial Services",
    personality_type: "Process Person",
    call_stage: "Demo / Pitch",
    difficulty_rating: 4,
    default_product: "client relationship management and compliance platform",
    language: "english",
  },
  {
    id: '95a1f4e9-d047-417a-8a6f-36c8a6a84474',
    name: "Anthony \u2014 Deep Dive: Financial Services (Alpha)",
    prospect_name: "Anthony Greco",
    prospect_role: "Managing Director",
    prospect_company: "Heritage Investment Partners",
    industry: "Financial Services",
    personality_type: "Alpha",
    call_stage: "Closing Call",
    difficulty_rating: 5,
    default_product: "client relationship management and compliance platform",
    language: "english",
  },
  {
    id: 'fb1176d4-e36c-434c-aca6-708c6ad60dfa',
    name: "Joyce \u2014 Deep Dive: EdTech (Urgency Seeker)",
    prospect_name: "Joyce Reyes",
    prospect_role: "VP Enrollment",
    prospect_company: "Westbrook Academy",
    industry: "EdTech",
    personality_type: "Urgency Seeker",
    call_stage: "Discovery Call",
    difficulty_rating: 2,
    default_product: "enrollment management and student retention platform",
    language: "english",
  },
  {
    id: 'df1f2caf-79b1-4731-a5b8-14ca9e08c997',
    name: "Eric \u2014 Deep Dive: EdTech (Ghost)",
    prospect_name: "Eric Donovan",
    prospect_role: "Director of Digital Learning",
    prospect_company: "Horizon EdTech",
    industry: "EdTech",
    personality_type: "Ghost",
    call_stage: "Objection Handling",
    difficulty_rating: 4,
    default_product: "enrollment management and student retention platform",
    language: "english",
  },
  {
    id: '232fc6be-2c28-4d2e-93f9-c8609a42cba9',
    name: "Jason \u2014 Deep Dive: E-commerce (Overanalyzer)",
    prospect_name: "Jason Kwon",
    prospect_role: "Co-Founder",
    prospect_company: "Vault Outdoors",
    industry: "E-commerce",
    personality_type: "Overanalyzer",
    call_stage: "Cold Call",
    difficulty_rating: 4,
    default_product: "customer acquisition and retention analytics platform",
    language: "english",
  },
  {
    id: '3654cbf8-a358-4760-afea-49390692ccf9',
    name: "Jessica \u2014 Deep Dive: E-commerce (Price Objector)",
    prospect_name: "Jessica Bloom",
    prospect_role: "Head of Growth",
    prospect_company: "Lumina Beauty",
    industry: "E-commerce",
    personality_type: "Price Objector",
    call_stage: "Negotiation",
    difficulty_rating: 5,
    default_product: "customer acquisition and retention analytics platform",
    language: "english",
  },
  {
    id: 'f2577f19-05d0-49e0-beb1-fb381bf7b137',
    name: "Steven \u2014 Deep Dive: Manufacturing (Friendly Waster)",
    prospect_name: "Steven Park",
    prospect_role: "COO",
    prospect_company: "Precision Parts Inc",
    industry: "Manufacturing",
    personality_type: "Friendly Waster",
    call_stage: "Discovery Call",
    difficulty_rating: 3,
    default_product: "ERP and production scheduling platform",
    language: "english",
  },
  {
    id: '95c6a7f1-d5e8-449b-a9ff-d804e51a6caa',
    name: "Donald \u2014 Deep Dive: Manufacturing (Gatekeeper)",
    prospect_name: "Donald Hicks",
    prospect_role: "VP of Operations",
    prospect_company: "Midwest Fabrication Co",
    industry: "Manufacturing",
    personality_type: "Gatekeeper",
    call_stage: "Objection Handling",
    difficulty_rating: 5,
    default_product: "ERP and production scheduling platform",
    language: "english",
  },
  {
    id: '7cf4c10b-0742-474b-8dc9-3b6396059e0d',
    name: "Patricia \u2014 Deep Dive: Insurance (Gatekeeper)",
    prospect_name: "Patricia Lee",
    prospect_role: "Managing Partner",
    prospect_company: "Guardian Agency LLC",
    industry: "Insurance",
    personality_type: "Gatekeeper",
    call_stage: "Cold Call",
    difficulty_rating: 4,
    default_product: "agency CRM and renewal management platform",
    language: "english",
  },
  {
    id: 'e38b4fe8-8e18-4583-aa7a-ab479734a8f2',
    name: "Sandra \u2014 Deep Dive: Insurance (Friendly Waster)",
    prospect_name: "Sandra Park",
    prospect_role: "Principal Agent",
    prospect_company: "Summit Benefits Group",
    industry: "Insurance",
    personality_type: "Friendly Waster",
    call_stage: "Closing Call",
    difficulty_rating: 5,
    default_product: "agency CRM and renewal management platform",
    language: "english",
  },
  {
    id: 'c35e9394-15cd-4f20-a11e-ddc2db6ff52d',
    name: "Jordan \u2014 The Founder/Buyer",
    prospect_name: "Jordan Wei",
    prospect_role: "CEO & Co-Founder",
    prospect_company: "BuildScale AI",
    industry: "SaaS",
    personality_type: "Alpha",
    call_stage: "Discovery Call",
    difficulty_rating: 5,
    default_product: "sales intelligence and CRM platform for early-stage SaaS companies",
    language: "english",
  },
  {
    id: '9d5f0bfa-a8a7-4e0c-8948-8ab285e7f030',
    name: "Morgan \u2014 New Manager, First 90 Days",
    prospect_name: "Morgan Banks",
    prospect_role: "VP of Sales (Newly Promoted)",
    prospect_company: "Clearview Capital",
    industry: "Financial Services",
    personality_type: "Process Person",
    call_stage: "Cold Call",
    difficulty_rating: 4,
    default_product: "client relationship management and compliance platform",
    language: "english",
  },
  {
    id: '51d8f867-f81a-4699-b7be-4e714630862c',
    name: "Alex \u2014 The Burned-Out Executive",
    prospect_name: "Alex Renner",
    prospect_role: "Chief Operating Officer",
    prospect_company: "Meridian Health Systems",
    industry: "Healthcare",
    personality_type: "Ghost",
    call_stage: "Follow-up",
    difficulty_rating: 5,
    default_product: "practice management and revenue cycle optimization platform",
    language: "english",
  },
  {
    id: 'bba04737-7887-4225-8c40-76042ec09d93',
    name: "Sam \u2014 The Blocked Champion",
    prospect_name: "Sam Okafor",
    prospect_role: "Director of Operations",
    prospect_company: "Titan Industrial Group",
    industry: "Manufacturing",
    personality_type: "Friendly Waster",
    call_stage: "Closing Call",
    difficulty_rating: 4,
    default_product: "ERP and production scheduling platform",
    language: "english",
  },
  {
    id: '37ed3d56-614c-4b76-8edd-995da7314021',
    name: "Committee \u2014 Three-Person Evaluation",
    prospect_name: "Panel: Dana, Chris & Riley",
    prospect_role: "Partner / IT Lead / Finance",
    prospect_company: "Ashford & Stern LLP",
    industry: "Legal",
    personality_type: "Overanalyzer",
    call_stage: "Demo / Pitch",
    difficulty_rating: 5,
    default_product: "legal practice management and billing platform",
    language: "english",
  },
  {
    id: 'bccbee53-2213-4500-a530-8f6fc3501713',
    name: "Quinn \u2014 The Dark Deal Re-engagement",
    prospect_name: "Quinn Torres",
    prospect_role: "CMO",
    prospect_company: "Vault Outdoors",
    industry: "E-commerce",
    personality_type: "Ghost",
    call_stage: "Cold Call",
    difficulty_rating: 4,
    default_product: "customer acquisition and retention analytics platform",
    language: "english",
  },
  {
    id: '058c7fd5-c9dd-48b5-9c89-74a97137ec30',
    name: "Drew \u2014 Existing Customer Upsell",
    prospect_name: "Drew Nakamura",
    prospect_role: "VP of Revenue",
    prospect_company: "DataPulse",
    industry: "SaaS",
    personality_type: "Skeptic",
    call_stage: "Discovery Call",
    difficulty_rating: 4,
    default_product: "advanced forecasting and AI insights module (upsell to existing CRM)",
    language: "english",
  },
  {
    id: '9dd66a86-b630-47a4-b5d7-9fdbf8f4fdc4',
    name: "Blake \u2014 Competitor's Customer",
    prospect_name: "Blake Simmons",
    prospect_role: "Agency Owner",
    prospect_company: "Pinnacle Insurance Group",
    industry: "Insurance",
    personality_type: "Burned Buyer",
    call_stage: "Cold Call",
    difficulty_rating: 5,
    default_product: "agency CRM and renewal management platform",
    language: "english",
  },
  {
    id: '6335b1d9-f4ee-4c34-8b4a-d801e6d8cfb3',
    name: "Casey \u2014 Procurement/Legal Final Hurdle",
    prospect_name: "Casey Walsh",
    prospect_role: "Procurement Manager",
    prospect_company: "Heritage Investment Partners",
    industry: "Financial Services",
    personality_type: "Process Person",
    call_stage: "Negotiation",
    difficulty_rating: 5,
    default_product: "client relationship management and compliance platform",
    language: "english",
  },
  {
    id: '520b9294-9fae-48e4-8b43-062acfc71660',
    name: "Reese \u2014 Technical Evaluator with Veto",
    prospect_name: "Reese Tanaka",
    prospect_role: "Head of Engineering / CTO",
    prospect_company: "VeloStack",
    industry: "SaaS",
    personality_type: "Overanalyzer",
    call_stage: "Demo / Pitch",
    difficulty_rating: 5,
    default_product: "sales intelligence and pipeline visibility platform",
    language: "english",
  },
]

export const MOCK_CARD = {
  opening_stat: 62,
  rapport_stat: 71,
  discovery_stat: 58,
  objection_stat: 45,
  closing_stat: 52,
  adaptability_stat: 67,
  overall_rating: 58,
  elo: 1240,
  rank_tier: 'Hunter',
  rank_title: 'Finding Your Prey',
  current_streak: 3,
  longest_streak: 7,
  total_calls: 24,
  calls_graded_b_or_above: 10,
}

export const MOCK_EVAL = {
  scores: {
    opening: 72,
    rapport: 68,
    discovery: 45,
    objection: 80,
    closing: 55,
    adaptability: 63,
  },
  grade: 'B',
  overall: 64,
  elo_change: 20,
  strengths: [
    'Strong opening hook at 0:15 — you acknowledged it was a cold call and asked for 30 seconds. Prospect stayed on the line.',
    'Handled the price objection at 2:45 smoothly — you redirected to ROI instead of defending the number.',
    'Good energy throughout. Voice stayed calm and confident even when challenged.',
  ],
  improvements: [
    "At 1:20, you jumped to pitching features before asking about their current setup. Try: 'Before I get into what we do, what does your current process look like for X?' Discovery first.",
    "You never asked for a next step. End of call at 4:30 was a soft 'I'll follow up' — that's a dead deal. Try: 'Are you open to a 20-minute look on Tuesday at 2pm?'",
    "Rapport section was generic small talk. Use specifics from their LinkedIn. 'I saw you just expanded to a second location — what triggered that?'",
  ],
  psychological_insights: {
    confidence_level: 'medium — some filler words ("uh", "so basically") but held composure under pressure',
    reciprocity_usage: 'weak — jumped straight to pitch without giving value first',
    social_proof_deployment: 'not used — missed opportunity when skepticism peaked at 2:00',
    loss_aversion_framing: "not used — framed as gain only ('you could save time') instead of loss ('you're losing $X/month')",
    empathy_calibration: 'moderate — acknowledged their concern but moved on too quickly',
    authority_signals: 'weak — no peer references, no market insights cited',
  },
  coach_note: "You have the raw instincts. The opening was solid and you didn't crumble under price pressure — that's actually harder than it looks. But you're leaving deals on the table by skipping discovery and not closing. A call without an ask for the next step is just a conversation. Every call needs to end with a concrete yes or no to a specific next step. Fix discovery and closing and your grade jumps to an A.",
}
